[versions]
moddev = "2.0.144"
minecraft = "26.2"
minecraftrange = "[26.2]"
neoforge = "26.2.0.64"

# 其他
mixinmcpdecompile = "0.9.0"
mixinsquared = "0.3.7-beta.3"

# 依赖
geckolib = "5.5.3"

# 联动
jei = "30.24.0.173"
jade = "26.2.9+neoforge"

## 本体
modLicense = "GNU GENERAL PUBLIC LICENSE"
# lib
libName = "Wild Wind Lib"
libVersions = "1.0.0"
libGroupId = "polari_stars.wild_wind.lib"
libId = "wild_wind_lib"
libEscription = """
Example mod description.
"""
# The Wild Update 荒野更新
thewildupdateName = "Wild Wind - The Wild Update"
thewildupdateVersion = "1.0.0"
thewildupdateGroup = "polari_stars.wild_wind.the_wild_update"
thewildupdateId = "wild_wind_the_wild_update"
thewildupdateDescription = """
Example mod description.
"""
# 主模块
mainId = "wild_wind_main"
mainName = "Wild Wind"
mainVersion = "1.0.0"
mainGroup = "polari_stars.wild_wind.main"
mainDescription = "Wild Wind main module."

[bundles]

[libraries]
# 其他
mixinsquared = { module = "com.github.bawnorton.mixinsquared:mixinsquared-neoforge", version.ref = "mixinsquared" }
# 依赖
geckolib = { module = "com.geckolib:geckolib-neoforge-26.2", version.ref = "geckolib" }
# 联动
jeiapi = { module = "mezz.jei:jei-26.2-neoforge-api", version.ref = "jei" }
jei = { module = "mezz.jei:jei-26.2-neoforge", version.ref = "jei" }
jade = { module = "maven.modrinth:jade", version.ref = "jade" }

[plugins]
moddev = { id = "net.neoforged.moddev", version.ref = "moddev" }
mixinmcpdecompile = { id = "dev.mixinmcp.decompile", version.ref = "mixinmcpdecompile" }

